export default function Head() {
  return (
    <>
      <title>Ecowitty.in</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
    </>
  );
}
